### ISSUE TITLE
Visualize graph? Add graphviz graph format?

### ISSUE THREAD

**Issue by jmmut** [gousiosg/java-callgraph#15]
Hey, nice concise tool!

Do you think it would be useful/easy to write the result in graphviz format? that way it would have a rudimentary way to visualize the graph. Maybe I missed something in the docs but the only output I saw is text based.

Maybe changing the current format, or adding a flag parameter, although I see it's currently straight to the point. 

I might get some time to do it myself, at least for the static part.

Let me know what you think.

**Comment by matthieu-vergne** [comment]
I am currently playing with Graphviz in combination with this tool, and I would not recommend to align them. This tool provides a list of dependencies (classes & calls), while Graphviz aims at visualizing graphs. Graphviz format (DOT language) has many features, with colors, styles, and so on. For a proper use, you would anyway need to adapt the result of java-callgraph to your liking. In this case, you would better make your own script to do so. It seems better to me to create a new tool integrating both java-callgraph & graphviz to do what you want.

**Comment by jmmut** [comment]
Sounds reasonable, thanks for the answer! :)
