### ISSUE TITLE
mvn build ran into problem, couldn't build jars using Java 11, Maven 3.6.3 on Ubuntu 20.04.01

### ISSUE THREAD

**Issue by nth347** [gousiosg/java-callgraph#33]
![image](https://user-images.githubusercontent.com/20441996/116677641-a4521080-a9d2-11eb-9c05-c275472a905a.png)

**Comment by ericwyles** [comment]
I am having the same problem on openjdk 11, Mac OS Big Sur, Maven 3.6.3

![image](https://user-images.githubusercontent.com/23637493/117360657-ad355d00-ae7e-11eb-8c4f-80a38eeaace9.png)

**Comment by ericwyles** [comment]
If I bypass the tests, it builds the jar and appears to work.

**Comment by zengxiaoliang** [comment]
may be skip the unit test case, it work

**Comment by nth347** [comment]
Thank you guys! It works now
